import { addDoc, collection, doc, serverTimestamp, updateDoc } from "firebase/firestore";
import { db } from "./firebase";

export const addDocument = async (collectionName: string, payload: object) => {
    try {
        // Reference the collection
        const collectionRef = collection(db, collectionName);
  
        // Add a new document with autogenerated ID
        await addDoc(collectionRef, {
          ...payload,
          createdAt: serverTimestamp(),
        });
  
      } catch (e) {
        console.error("Error adding document: ", collectionName, e);
      }
}

export const updateDocument = async (collectionName: string, payload: object, docId: string,) => {
    try {
        // Reference the collection
        const collectionRef = doc(db, collectionName, docId);
  
        // update a old document 
         await updateDoc(collectionRef, {
          ...payload,
        });
  
      } catch (e) {
        console.error("Error update document: ", collectionName, e);
      }
}